from enum import StrEnum


class ErrorCode(StrEnum):
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_ALREADY_EXISTS = "DOCUMENT_ALREADY_EXISTS"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"

    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"

    CHAT_CONTEXT_TOO_LARGE = "CHAT_CONTEXT_TOO_LARGE"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"